### ISSUE TITLE
Undefined variable when using an example

### ISSUE THREAD

**Issue by akrzos** [jaredoconnell/cluster-impairment-operator#3]
I ran into this issue in the operator logs while trying out the examples:

```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'node_selector'\n\nThe error appears to be in '$
opt/ansible/playbooks/roles/deploy-impairment-workers/tasks/main.yml': line 50, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appe$
rs to be:\n\n\n    - name: Deploy Daemonset\n      ^ here\n"}
```

It seems we must always define a node_selector.  We should either include the node_selector fields in the examples or fix it to choose the default anyhow.

**Comment by jaredoconnell** [comment]
I literally pushed a commit to fix this seconds ago. Does it work now?

**Comment by akrzos** [comment]
> I literally pushed a commit to fix this seconds ago. Does it work now?

I pulled the latest and it is fixed now.  Thanks Jared.
